version: "3"


services:
  restapi_db:
    image: "postgres:11"
    container_name: "restapi_db"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    ports:
      - "54320:5432"
    volumes:
      - /home/pgdata:/var/lib/postgresql/data
     